Repository jupyterlab/jupyter-builder, pull requests merged in 2024-07, with the labels that each got.

#13 Build feature and Tests
  .pre-commit-config.yaml
  jupyter_builder/base_extension_app.py
  jupyter_builder/core_path.py
  jupyter_builder/extension_commands/build.py
  jupyter_builder/federated_extensions.py
  jupyter_builder/jupyterlab_server_req.py
  jupyter_builder/main.py
  pyproject.toml
  tests/test_tpl.py
Labels: enhancement

#18 Watch feature and tests
  jupyter_builder/extension_commands/watch.py
  jupyter_builder/federated_extensions.py
  jupyter_builder/jlpm.py
  jupyter_builder/main.py
  pyproject.toml
  tests/test_tpl.py
Labels: enhancement

#22 Documentation
  README.md
Labels: documentation

#23 Scaffolding for adding a npm package and setting up the releaser
  .copier-answers.yml
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/python-tests.yml
  .gitignore
  .licenserc.yaml
  .pre-commit-config.yaml
  .prettierignore
  .yarnrc.yml
  LICENSE
  README.md
  RELEASE.md
  jupyter_builder/__init__.py
  package.json
  pyproject.toml
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: maintenance

#25 Comment npm related release hook
  pyproject.toml
Labels: bug

#26 Update README.md 2
  .prettierignore
  README.md
Labels: documentation
